version: "1"
services:
  galaxy-lappsgrid:
    image: bgruening/galaxy-stable:latest
    working_dir: '/galaxy-central'
    command: ['/usr/bin/startup']
    volumes:
      - /export/
      - /data/
      - /var/lib/docker
    expose:
      - "80"
      - "21"
      - "22"
      - "8000"
      - "8800"
      - "9002"
  vassar:
    image: lappsgrid/tomcat7
    user: 'root'
    command: ["/usr/bin/startup"]

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
