version: "1"
services:
  galaxy-lappsgrid:
    image: bgruening/galaxy-stable:latest
    working_dir: '/galaxy-central'
    command: ['/usr/bin/startup']
    volumes:
      - /export/
      - /data/
      - /var/lib/docker
    expose:
      - "80"
      - "21"
      - "22"
      - "8000"
      - "8800"
      - "9002"
  vassar:
    image: lappsgrid/tomcat7
    user: 'root'
    command: ["/usr/bin/startup"]

  oaqa:
    image: lappsgrid/tomcat7
    user: 'root'
    command: ["/usr/bin/startup"]

  ubuntu:
    image: ubuntu:14.04

  lapps-ubuntu:
    image: lappsgrid/ubuntu

    
  brandeis:
    image: lappsgrid/tomcat7
    user: 'root'
    command: ["/usr/bin/startup"]

  gigaworld:
    image: lappsgrid/gigaworld
    user: 'root'

  masc:
    image: lappsgrid/tomcat7:1.0.0
    user: 'root'
    command: ["/usr/bin/startup"]

  service-manager:
    image: lappsgrid/ubuntu
    user: 'root'
    command: [ "/usr/bin/startup" ]

  service-manager-vassar:
    image: lappsgrid/service-manager
    user: 'root'
    command: [ "/usr/bin/startup" ]

  service-manager-full:
    image: lappsgrid/service-manager:vassar
    working_dir: 'etc/lddl'

  service-manager-brandeis:
    image: ksuderman/service-manager:base
    user: 'root'
    command: [ "/usr/bin/startup" ]

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx
