- hosts: galaxy-lappsgrid
  tasks:
    - name: Install linux packages
      raw: apt-get update && apt-get install -y bash emacs24-nox git
    - name: Permissions Fix
      raw: chmod -R 700 /galaxy-central/
    - name: Add tools
      copy: src="./files/galaxy-lappsgrid/tools" dest="/galaxy-central/tools"
    - name: Add Index
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-galaxy-lappsgrid/master/index.html dest=/galaxy-central/index.html
    - name: Add Tool Conf file
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-galaxy-lappsgrid/master/tool_conf.xml dest=/galaxy-central/tool_conf.xml
    - name: Add Galaxy file
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-galaxy-lappsgrid/master/galaxy.ini dest=/galaxy-central/galaxy.ini
    - name: Add Welcome file
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-galaxy-lappsgrid/master/welcome.html dest=/galaxy-central/welcome.html
    - name: Add Tool Shed Conf
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-galaxy-lappsgrid/master/tool_sheds_conf.xml dest=/galaxy-central/tool_shed_conf.xml
    - name: Add startup.sh
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-galaxy-lappsgrid/master/startup.sh dest=/galaxy-central/startup.sh

- hosts: vassar
  tasks:
    - name: Get SET_ENV script
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-vassar/master/setenv.sh dest=/usr/share/tomcat7/bin/setenv.sh
    - name: Get Shutdown script
      get_url: url=https://raw.githubusercontent.com/lappsgrid-incubator/docker-vassar/master/shutdown.sh dest=/usr/bin/shutdown
